name: blood_pressure_measurement
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  avatar_glow: ^3.0.1
  calendar_date_picker2: ^0.5.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  gap: ^3.0.1
  get: ^4.6.6
  heart_bpm: ^2.0.0+0
  lottie: ^3.0.0
  lucide_icons: ^0.257.0
  smooth_page_indicator: ^1.1.0
  torch_light: ^1.0.0

flutter_launcher_icons:
  ios: true
  min_sdk_android: 26
  remove_alpha_ios: true
  android: "launcher_icon"
  image_path: "assets/icon/icon-min.png"

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Black.ttf
        - asset: assets/fonts/Inter/Inter-Bold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter/Inter-Light.ttf
        - asset: assets/fonts/Inter/Inter-Medium.ttf
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter/Inter-Thin.ttf
